services:
  apache2:
    build: ./docker/apache2
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
    depends_on:
      - php-fpm
    networks:
      - laranet

  php-fpm:
    build: ./docker/php
    volumes:
      - ./src:/var/www/src/
    networks:
      - laranet

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laranet

volumes:
  db_data:

networks:
  laranet:
